[project]
name = "english-center-manager-databaseproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "PyQt6",
    "pyodbc",
    "requests>=2.32.5",
]
